[build]
builder = "NIXPACKS"
watchPatterns = ["backend/**"]

[deploy]
startCommand = "cd backend && npx prisma db push --accept-data-loss && node dist/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

