services:
  - type: web
    name: razorpayx-payroll-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run db:generate && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    disk:
      name: sqlite-data
      mountPath: /app/backend/prisma
      sizeGB: 1

